workflows:
  ios-workflow:
    name: MoneyControl iOS

    instance_type: mac_mini_m2

    environment:
      node: 20

    scripts:
      - npm ci
      - npm run build
      - npx cap sync ios
      - cd ios/App
      - pod install

    artifacts:
      - ios/App/build/**/*.ipa
      - ios/App/build/**/*.app